### PR TITLE
Update config.js

### PR DESCRIPTION
**Pull request by watafakman**

### CODE REVIEW

**Comment by Rdmo1** [comment]
done

**Comment by londonplayzlol** [comment]
why you scaming man i deleted ur webhook like 69 times!

**Comment by londonplayzlol** [comment]
`skid am reproting to github`

**Comment by letruxux** [comment]
how do i dm you on discord @Rdmo1 if you have your dms disabled

**Comment by mte0** [comment]
im 99% sure this is a rat.

**Comment by mte0** [comment]
its a rat

**Comment by lordhackermen** [comment]
its a rat yes. its a cookie-logger

**Comment by lordhackermen** [comment]
this thing is not open-sources.

**Pull request closed without merging**
